# Generated by Django 2.2.7 on 2019-11-20 23:39

from django.db import migrations, models
import pitter.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=32)),
                ('hash_of_password_with_salt', models.BinaryField(max_length=32)),
                ('salt_for_password', models.BinaryField(max_length=16)),
                ('email_address', models.CharField(blank=True, max_length=254)),
                ('email_notifications_enabled', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
