# Generated by Django 2.2.7 on 2019-12-05 21:38

import django.db.models.expressions
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, follower__exact=django.db.models.expressions.F('following')),
                name='forbid to follow yourself',
            ),
        ),
    ]
