# Generated by Django 2.2.7 on 2019-11-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitter', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
